version: "3.9"

services:
  api:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./flaskr:/app/flaskr
    depends_on:
      - database
  database:
    image: "mysql:8.0.26"        
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    